server:
  port: 8080
logging:
  level:
    ROOT: INFO
    ru:
      otus: TRACE
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/library?createDatabaseIfNotExist=true
    username: library
    password: library
  enableMigration: true
  jpa:
    properties:
      hibernate:
        jdbc:
          lob.non_contextual_creation: true
library:
  api: http://localhost:8080/api










